owner: mikemhenry
repo: website-uptime 

sites:
  - name: OMSF
    url: https://www.omsf.io
  - name: OpenFE
    url: https://openfree.energy
  - name: Try OpenFE
    url: https://try.openfree.energy
    maxResponseTime: 10000
  - name: OpenFF
    url: https://openforcefield.org
  - name: Alchemiscale (API)
    url: https://api.alchemiscale.org/ping
  - name: Alchemiscale (Compute)
    url: https://compute.alchemiscale.org/ping

assignees: # Users to assign downtime issues (optional)
  - mikemhenry

status-website:
  cname: status.MKN7787.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status Page for OMSF Project Webpages"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/mikemhenry/website-status).
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
