owner: mikemhenry
repo: website-uptime 

sites:
  - name: OMSF
    url: https://www.omsf.io
  - name: OpenFE
    url: https://openfree.energy
  - name: OpenFF
    url: https://openforcefield.org

assignees: # Users to assign downtime issues (optional)
  - mikemhenry

status-website:
  cname: status.MKN7787.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status Page for OMSF Project Webpages"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/mikemhenry/website-status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
